---
title: "Analysis"
author: "Nathanael Larigaldie"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(viridis)
library(gt)
```

```{r include=FALSE}
list_files <- list.files(path = file.path("..", "Analysis", "Blinded"), pattern = "*.csv$")

for(file in list_files)
{
  blinded <- read_csv(file.path("..", "Analysis", "Blinded", file))
  complete <- read_csv(file.path("..", "Analysis", "Complete", file))

  complete$X <- blinded$X
  complete$Y <- blinded$Y
  complete$X.Error <- blinded$X.Error
  complete$Y.Error <- blinded$Y.Error
  if("Comment" %in% colnames(blinded))
  {
    complete <- complete %>% filter(is.na(blinded$Comment)) 
  }
  complete$Euclidian.Distance <- sqrt((complete$X - complete$Corrected.Fixation.X)**2
                                      + (complete$Y - complete$Corrected.Fixation.Y)**2)
  complete$Website <- strsplit(file, "_", fixed=TRUE)[[1]][1]
  complete <- complete %>% mutate(Website = ifelse(Website=="S1", "Test page 1",
                                            ifelse(Website=="S2", "Test page 2",
                                            ifelse(Website=="S3", "PsychoPy",
                                                   "OSF"))))
  if(grepl("iMotions", file, fixed=TRUE))
  {
    complete$Setting <- "iMotions, 1920*1080"
  }
  else
  {
    complete$Setting <- ifelse(grepl("1050", file, fixed=TRUE),
                               "EyeLink, 1680*1050",
                               ifelse(grepl("1080", file, fixed=TRUE),
                                      "EyeLink, 1920*1080",
                                      "EyeLink, 1920*1200"))
  }
  if (!exists("d"))
  {
    d <- complete
  }
  else
  {
    d <- rbind(d, complete)
  }
}
write_csv(d, file.path("..", "Analysis", "Final", "final_dataset.csv"))
```

## Plots

```{r, echo=FALSE}
d$all <- "all"
d2 <- d
d <- d %>% filter(Euclidian.Distance <=10)
d %>% ggplot( aes(x=Website, y=Euclidian.Distance, fill=Website)) +
    geom_violin(width=1) +
    geom_boxplot(width=0.2, color="darkgrey", alpha=0.8, size=1) +
    scale_fill_viridis(discrete = TRUE) +
    theme_minimal() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
  ggtitle("Errors per website") +
  xlab("Website") +
  ylab("Euclidian Distance")

d %>% ggplot( aes(x=Setting, y=Euclidian.Distance, fill=Setting)) +
    geom_violin(width=1) +
    geom_boxplot(width=0.2, color="darkgrey", alpha=0.8, size=1) +
    scale_fill_viridis(discrete = TRUE) +
    theme_minimal() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
  ggtitle("Errors per study setting") +
  xlab("Study setting") +
  ylab("Euclidian Distance")

d %>% ggplot(aes(x=all, y=Euclidian.Distance, fill=all)) +
    geom_violin(width=1) +
    geom_boxplot(width=0.2, color="darkgrey", alpha=0.8, size=1) +
    scale_fill_viridis(discrete = TRUE) +
    theme_minimal() +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
  ggtitle("Errors total") +
  xlab("") +
  ylab("Euclidian Distance")

d %>%
  group_by(Website) %>%
  summarize(mean=mean(Euclidian.Distance), 
            sd=sd(Euclidian.Distance),
            median=median(Euclidian.Distance)) %>%
  gt()

d %>%
  group_by(Setting) %>%
  summarize(mean=mean(Euclidian.Distance), 
            sd=sd(Euclidian.Distance),
            median=median(Euclidian.Distance)) %>%
  gt()

d %>%
  group_by(all) %>%
  summarize(mean=mean(Euclidian.Distance), 
            sd=sd(Euclidian.Distance),
            median=median(Euclidian.Distance)) %>%
  gt()

cat("n data: ", nrow(d2), "\n")
cat("n errors: ", nrow(d2 %>% filter(Euclidian.Distance > 10)), "\n")
cat("% errors: ", (nrow(d2 %>% filter(Euclidian.Distance > 10)) / nrow(d2))*100, "\n")
cat("n manual errors: ", nrow(d2 %>% filter(!is.na(X.Error), X.Error !="ND")), "\n")
cat("% manual errors: ", (nrow(d2 %>% filter(!is.na(X.Error), X.Error !="ND")) / nrow(d2))*100, "\n")

cat("average manual error: ",
    mean((d2 %>% filter(!is.na(X.Error), X.Error !="ND") %>%
            mutate(Euclidian.Distance.Error =
                     sqrt((as.numeric(X.Error) -
                             Corrected.Fixation.X)**2 +
                            (as.numeric(Y.Error) - Corrected.Fixation.Y)**2)
                   ))$Euclidian.Distance.Error), "\n")
cat("average eyeScrollR error: ",
    mean((d2 %>% filter(Euclidian.Distance > 10))$Euclidian.Distance), "\n")

```
